#!/usr/bin/env python3
"""Single source of truth for the podcast section.

Fetches the RSS feed and regenerates:
  * _data/podcast_channel.yml   (title / description / cover — the top intro)
  * _podcast/ep-NN.md           (one file per episode)
  * assets/img/podcast/cover.jpg

Idempotent and safe to re-run (weekly cron or manual). It PRESERVES:
  * locally-added transcripts        (the `transcript:` front-matter key + _data/transcripts/*.json)
  * manual platform links            (spotify / xiaoyuzhou — not present in the RSS feed)

Standard library only (no pip deps) so it runs anywhere, including CI.
"""
import os, re, html, sys, json
import xml.etree.ElementTree as ET
from urllib.parse import unquote
from urllib.request import urlopen, Request
from datetime import datetime

FEED = "https://anchor.fm/s/fb64b404/podcast/rss"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POD = os.path.join(ROOT, "_podcast")
DATA = os.path.join(ROOT, "_data")
CHANNEL_YML = os.path.join(DATA, "podcast_channel.yml")
COVER = os.path.join(ROOT, "assets", "img", "podcast", "cover.jpg")
NS = {"itunes": "http://www.itunes.com/dtds/podcast-1.0.dtd"}

# Links not present in the RSS feed — kept as defaults, overridden by whatever
# is already in podcast_channel.yml so manual edits survive a re-sync.
MANUAL_DEFAULTS = {"apple": "https://podcasts.apple.com/us/podcast/%E5%92%8Cgeorgia%E8%81%8A%E5%A4%A9/id1773696192",
                   "spotify": "https://open.spotify.com/show/6bKusctv5UE1tV4noL2BUU",
                   "xiaoyuzhou": "https://www.xiaoyuzhoufm.com/podcast/670c88d60d2f24f289e5adc7"}


def fetch(url):
    return urlopen(Request(url, headers={"User-Agent": "podcast-sync/1.0"}), timeout=60).read()


def read_manual_links():
    """Preserve manually-maintained platform links from an existing channel file."""
    links = dict(MANUAL_DEFAULTS)
    if os.path.exists(CHANNEL_YML):
        for line in open(CHANNEL_YML, encoding="utf-8"):
            m = re.match(r"^(apple|spotify|xiaoyuzhou):\s*(.*)$", line.strip())
            if m and m.group(2):
                links[m.group(1)] = m.group(2).strip().strip('"')
    return links


def existing_transcript_key(slug):
    """Keep the transcript wiring if this episode file already exists."""
    path = os.path.join(POD, f"{slug}.md")
    if os.path.exists(path):
        m = re.search(r"^transcript:\s*(\S+)\s*$", open(path, encoding="utf-8").read(), re.M)
        if m and m.group(1) not in ("false", "null", "~"):
            return m.group(1)
    return "false"


def clean_paragraphs(raw):
    out = []
    for p in re.findall(r"<p>(.*?)</p>", raw, flags=re.S):
        p = re.sub(r"<br\s*/?>", "", p)
        p = re.sub(r"<[^>]+>", "", p)
        p = html.unescape(p).strip()
        if p:
            out.append(p)
    return out


def epnum(title):
    m = re.search(r"[Ee][Pp]\s*-?\s*0*(\d+)", title)
    return int(m.group(1)) if m else 0


def decode_audio(u):
    m = re.search(r"/play/\d+/(https.*)$", u)
    return unquote(m.group(1)) if m else u


def yq(s):
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'


def fetch_apple_episodes():
    """Map episode number -> that episode's Apple Podcasts URL (best effort)."""
    out = {}
    try:
        data = json.loads(fetch("https://itunes.apple.com/lookup?id=1773696192"
                                "&media=podcast&entity=podcastEpisode&limit=100").decode())
        for r in data.get("results", []):
            url = r.get("trackViewUrl") or r.get("episodeUrl")
            n = epnum(r.get("trackName") or "")
            if n and url:
                out[n] = url.split("&uo=")[0]
    except Exception as e:
        print(f"! apple episode lookup failed: {e}")
    return out


def main():
    xml = fetch(FEED)
    ch = ET.fromstring(xml).find("channel")

    # ---- channel meta (the top intro, synced from RSS) ----
    title = (ch.findtext("title") or "").strip()
    desc = (ch.findtext("description") or "").strip()
    img_el = ch.find("itunes:image", NS)
    cover_url = img_el.get("href") if img_el is not None else None
    if cover_url:
        try:
            os.makedirs(os.path.dirname(COVER), exist_ok=True)
            open(COVER, "wb").write(fetch(cover_url))
        except Exception as e:
            print(f"! cover download failed: {e}")

    links = read_manual_links()
    os.makedirs(DATA, exist_ok=True)
    with open(CHANNEL_YML, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/sync_podcast.py from the RSS feed.\n")
        f.write("# title / description / cover come from RSS; apple/spotify/xiaoyuzhou are manual.\n")
        f.write(f"title: {yq(title)}\n")
        f.write(f"description: {yq(desc)}\n")
        f.write("cover: /assets/img/podcast/cover.jpg\n")
        f.write(f"rss: {yq(FEED)}\n")
        f.write(f"apple: {yq(links['apple'])}\n")
        f.write(f"spotify: {yq(links['spotify'])}\n")
        f.write(f"xiaoyuzhou: {yq(links['xiaoyuzhou'])}\n")
    print(f"channel: {title} ({len(desc)} char desc)")

    # ---- episodes ----
    apple_eps = fetch_apple_episodes()
    os.makedirs(POD, exist_ok=True)
    new, updated = 0, 0
    for it in ch.findall("item"):
        etitle = (it.findtext("title") or "").strip()
        n = epnum(etitle)
        if not n:
            continue
        slug = f"ep-{n:02d}"
        enc = it.find("enclosure")
        audio = decode_audio(enc.get("url")) if enc is not None else ""
        dur = (it.findtext("{http://www.itunes.com/dtds/podcast-1.0.dtd}duration") or "").strip()
        if dur.startswith("00:"):
            dur = dur[3:]
        date = datetime.strptime((it.findtext("pubDate") or "").strip(),
                                 "%a, %d %b %Y %H:%M:%S %Z").strftime("%Y-%m-%d")
        guid = (it.findtext("guid") or "").strip()

        paras = clean_paragraphs(it.findtext("description") or "")
        ts_re = re.compile(r"^\s*(\d{1,2}:\d{2})")
        intro_lines = [p for p in paras if not ts_re.match(p)]      # 简介 + 总结, kept together
        ts_lines = [p for p in paras if ts_re.match(p)]             # 时间轴, separate section
        summary = intro_lines[0] if intro_lines else ""            # short blurb for the listing

        # timestamps -> structured front-matter list ("mm:ss desc")
        timestamps = []
        for t in ts_lines:
            mm = re.match(r"^\s*(\d{1,2}:\d{2})\s*[:：]?\s*(.*)$", t)
            timestamps.append(f"{mm.group(1)} {mm.group(2).strip()}" if mm else t)

        fm = ["---", "layout: podcast", f"number: {n}", f"title: {yq(etitle)}",
              f"date: {date}", f"duration: {yq(dur)}", f"audio: {yq(audio)}",
              f"guid: {yq(guid)}", f"summary: {yq(summary)}",
              f"apple_episode: {yq(apple_eps.get(n, ''))}",
              f"transcript: {existing_transcript_key(slug)}"]
        if timestamps:
            fm.append("timestamps:")
            fm += [f"  - {yq(t)}" for t in timestamps]
        fm.append("---")
        # body = the intro/summary block only (one continuous section)
        body = "\n\n".join(intro_lines)
        content = "\n".join(fm) + "\n\n" + body.rstrip() + "\n"

        path = os.path.join(POD, f"{slug}.md")
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old is None:
            new += 1
        elif old != content:
            updated += 1
        if old != content:
            open(path, "w", encoding="utf-8").write(content)

    print(f"episodes: {new} new, {updated} updated")


if __name__ == "__main__":
    sys.exit(main())
